### ISSUE TITLE
Capture system back/play/next events

### ISSUE THREAD

**Issue by shawnwall** [shawnwall/GrooveX#1]

**Comment by shawnwall** [comment]
implemented

**Comment by tjmgregory** [comment]
Hi there, love the idea and have been using it a lot. On El Capitan, the media key press seems to be received twice, so music will pause and immediately play again, and two tracks are skipped instead of one.
If you're busy I'll happily look into it for you in a months time after my exams, I like what you've done and would be eager to help out.

**Comment by shawnwall** [comment]
Feel free to investigate when you can, as I no longer have a paid Groove account to test with. My guess is they changed something in their js given we're dependent on those calls. I can say it was definitely working correctly at one point :)

**Comment by tjmgregory** [comment]
Sweet, will do. Hopefully I'll come up with a solution :)
